In [1]:
import lancedb as ld

In [2]:
db = ld.connect("data/lance")

In [3]:
table = db.open_table("files")

In [ ]:
from pathlib import Path

Path("data/to_index_small_2").absolute()

PosixPath('/home/work/16525722@sigma.sbrf.ru/projects/rag-files-back/data/to_index_small_2')

In [ ]:
import polars as pl

pl.DataFrame(table.to_arrow())

shape: (33, 5)
┌─────┬───────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┐
│ idx ┆ text                  ┆ meta                 ┆ path                 ┆ vector               │
│ --- ┆ ---                   ┆ ---                  ┆ ---                  ┆ ---                  │
│ i64 ┆ str                   ┆ struct[9]            ┆ str                  ┆ array[f32, 312]      │
╞═════╪═══════════════════════╪══════════════════════╪══════════════════════╪══════════════════════╡
│ 0   ┆ ## Intelligent Search ┆ {2025-09-12          ┆ /home/work/16525722@ ┆ [-0.032284,          │
│     ┆                       ┆ 17:28:28.624337,20…  ┆ sigma.sbrf…          ┆ -0.030977, … 0.029…  │
│     ┆ [ЦК По …              ┆                      ┆                      ┆                      │
│ 1   ┆ #### **450+**         ┆ {2025-09-12          ┆ /home/work/16525722@ ┆ [-0.074748,          │
│     ┆                       ┆ 17:28:28.624337,20…  ┆ sigma.sbrf…          ┆ 0.037952, … 0.0283…  │
│     ┆                       ┆                      ┆                      ┆                      │
│     ┆ **Сервисы Плат…       ┆                      ┆                      ┆                      │
│ 2   ┆ **Доступ к            ┆ {2025-09-12          ┆ /home/work/16525722@ ┆ [-0.089773,          │
│     ┆ корпоративным источ…  ┆ 17:28:28.624337,20…  ┆ sigma.sbrf…          ┆ 0.001561, … -0.001…  │
│ 3   ┆ |№|Проект|Клиент|Блок ┆ {2025-09-12          ┆ /home/work/16525722@ ┆ [-0.074905,          │
│     ┆ |Статус|И…            ┆ 17:28:28.624337,20…  ┆ sigma.sbrf…          ┆ -0.006716, … -0.00…  │
│ 4   ┆ |10|Поиск в           ┆ {2025-09-12          ┆ /home/work/16525722@ ┆ [-0.128817,          │
│     ┆ SberSpace|SberWork…   ┆ 17:28:28.624337,20…  ┆ sigma.sbrf…          ┆ 0.002816, … -0.000…  │
│ …   ┆ …                     ┆ …                    ┆ …                    ┆ …                    │
│ 0   ┆ Рекомендательные      ┆ {2025-09-29          ┆ /home/work/16525722@ ┆ [-0.019993,          │
│     ┆ модели (Друг)…        ┆ 13:39:59.938934,20…  ┆ sigma.sbrf…          ┆ -0.009283, … 0.017…  │
│ 0   ┆ Требования к отчету о ┆ {2025-09-29          ┆ /home/work/16525722@ ┆ [-0.002812,          │
│     ┆ разработ…             ┆ 13:40:00.142931,20…  ┆ sigma.sbrf…          ┆ -0.010266, … -0.03…  │
│ 1   ┆ продукт, канал        ┆ {2025-09-29          ┆ /home/work/16525722@ ┆ [0.036103, 0.011345, │
│     ┆ продаж, канал к…      ┆ 13:40:00.142931,20…  ┆ sigma.sbrf…          ┆ … 0.01924…           │
│ 2   ┆ описаны планируемые   ┆ {2025-09-29          ┆ /home/work/16525722@ ┆ [-0.052388,          │
│     ┆ пилоты для…           ┆ 13:40:00.142931,20…  ┆ sigma.sbrf…          ┆ 0.024643, … 0.0138…  │
│ 3   ┆ длинный список        ┆ {2025-09-29          ┆ /home/work/16525722@ ┆ [-0.062954,          │
│     ┆ факторов (для п…      ┆ 13:40:00.142931,20…  ┆ sigma.sbrf…          ┆ -0.055237, … 0.010…  │
└─────┴───────────────────────┴──────────────────────┴──────────────────────┴──────────────────────┘

In [5]:
import polars as pl

df = pl.DataFrame(table.to_arrow())
df.select(pl.col.path.n_unique())

shape: (1, 1)
┌──────┐
│ path │
│ ---  │
│ u32  │
╞══════╡
│ 18   │
└──────┘

In [32]:
table.create_fts_index("text", tokenizer_name="ru_stem", replace=True)

In [5]:
from src.config import Config

q = "резюме воробьев"
vec = Config().embed_query([q])[0]
table.search(query_type="hybrid").text(q).vector(vec).limit(10).to_polars()

/Users/admin/projects/work/files-search-back/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

RuntimeError: lance error: Invalid user input: query dim(1024) doesn't match the column vector vector dim(312), /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lance-0.33.0/src/dataset/scanner.rs:1012:25

In [19]:
from IPython.display import Markdown, display

display(
    Markdown(
        df.filter(pl.col.text.str.to_lowercase().str.contains("воробьев"))
        .select(pl.col.text)
        .to_series()
        .to_list()[0]
    )
)

# **Воробьев Тимур Николаевич**

Мужчина, 28 лет, родился 9 августа 1996


+7 (925) 0307091

vorobiev.timur96@gmail.com — предпочитаемый способ связи


Проживает: Москва
Гражданство: Россия, есть разрешение на работу: Россия

Готов к переезду: Беларусь, Грузия, Другие регионы, Казахстан, готов к редким командировкам


Желаемая должность и зарплата


**Аналитик управления аналитики и моделирования**


Специализации:

— Аналитик

— Программист, разработчик
Занятость: полная занятость, частичная занятость, проектная работа
График работы: полный день, гибкий график, удаленная работа
Желательное время в пути до работы: не имеет значения


Опыт работы — 4 года 8 месяцев



Январь 2023 —

настоящее время
2 года 1 месяц


Август 2021 —

Июль 2022

1 год


Июль 2020 —

Август 2021
1 год 2 месяца



**TELE2 Россия**

Москва, www.ru.tele2.ru/

Телекоммуникации, связь

  - Мобильная связь


Эксперт по обработке больших данных (Data scientist).


Разработка моделей антифрода. Разработка моделей верификации клиентов на сайтах,
детектирование флешколлтов, поиск фрода.


**Яндекс**
www.yandex.ru
Информационные технологии, системная интеграция, интернет

  - Интернет-компания (поисковики, платежные системы, соц.сети,
информационно-познавательные и развлекательные ресурсы, продвижение сайтов и

прочее)


Аналитик (Data scientist, Data analyst в поиске и рекомендации Яндекс
Маркет)


Машинное обучение в поиске и рекомендациях в Яндекс.Маркет. Настройка разметки и
пайплайнов обработки данных. Отвечал за разработку и поддержку моделей и метрик в

моделях поиска, каталога и редиректов, проведения A/B-тестирования.


**Сбер**
rabota.sber.ru/

Финансовый сектор

  - Банк


Исследователь данных (data scientist по направлению Розничные
риски)


Разработка моделей оценки розничных рисков в направлении ПВР с использованием
табличных данных и в направлении коллекшн с использованием графовых данных и текстов
расшифровок разговоров с клиентами.



Резюме обновлено 14 января 2025 в 13:12


Сентябрь 2019 —
Февраль 2020
6 месяцев


Образование


Высшее



**АО ДОМ.РФ**


Ведущий специалист( валидация моделей банковских рисков)


Валидация и улучшение моделей проектного финансирования и кредитного риска.



2020 **Московский государственный университет им. М.В. Ломоносова,**
**Москва**